### ISSUE TITLE
Returning the value from @class.session

### ISSUE THREAD

**Issue by Originn** [aspenforest/yfrake#3] opened 2022-05-04 06:30 UTC
Trying to return the raw price using the following test code but always get a return of None. I am testing it on Flask. If I print the result, there is no issue. I am still a learner and it seems that it's a decorator. Any advice on how to return the value?

```
@client.session
def main(user_input):
    final_list=[]
    stock_list=[]
    stock_list.append(user_input)
    queries=[]
    for i in stock_list:
        queries.append(dict(endpoint='price_overview', symbol=i))
    results = client.batch_get(queries)
    for resp in results.gather():
        final_list.append(resp.data["regularMarketPrice"]["raw"])
    return final_list[0]
```

**Comment by aabmets** [comment] 2022-05-06 22:28
@Originn Well first of all, you're returning the first element of the **final_list**, not the whole list itself and second, have you tried using Yfrake without Flask? If the code works without Flask, then the problem is in Flask. Since I do not know Flask internals, I could not even begin to assume how one could affect the other. Try without Flask and if it works, then I would suggest to work around Flask. Are you using Flask, because the built-in server of Yfrake is insufficient for your needs? You could just run the built-in server from your code and then use the regular **requests** library to request data from http://localhost:8888 (default).

**Comment by Originn** [comment] 2022-05-08 06:59
@aabmets Thanks for your replay! I tested it without flask and the following will print [157.28]

```
@client.session
def main(user_input):
    final_list=[]
    stock_list=[]
    stock_list.append(user_input)
    queries=[]
    for i in stock_list:
        queries.append(dict(endpoint='price_overview', symbol=i))
    results = client.batch_get(queries)
    for resp in results.gather():
        final_list.append(resp.data["regularMarketPrice"]["raw"])
    print(final_list)

main('aapl')
```

But trying to return it using the following return None:

```
@client.session
def main(user_input):
    final_list=[]
    stock_list=[]
    stock_list.append(user_input)
    queries=[]
    for i in stock_list:
        queries.append(dict(endpoint='price_overview', symbol=i))
    results = client.batch_get(queries)
    for resp in results.gather():
        final_list.append(resp.data["regularMarketPrice"]["raw"])
    return final_list

stock = main('aapl')
print(stock)
```

Will it be possible to add an option to return a value in the decorator function?

**Comment by aabmets** [comment] 2022-05-08 07:12
@Originn May I see your Flask code, how **Yfrake** fits into it?

**Comment by Originn** [comment] 2022-05-08 07:55
@aabmets The code can be found on https://github.com/Originn/AdvancedPortOpt/blob/main/application.py and I use the function below the imports and above app=Flask(__name__).

I don't think it's a Flask issue though as it does not return a value when I tested it without Flask.

**Comment by aabmets** [comment] 2022-05-08 08:04
@Originn have you tried printing **resp.error**? If **resp.data** returns None, then the request made to the **Yahoo** servers was invalid or **Yfrake** could not connect to **Yahoo** servers.
EDIT: By an invalid request I mean that the args passed to the client methods were invalid.

**Comment by aabmets** [comment] 2022-05-08 08:30
@Originn 
This code works:
```
from yfrake import client
from flask import Flask


app = Flask(__name__)


@client.session
def run_flask():
    global app
    app.run()


@app.route("/price_overview")
def get_price_overview():
    resp = client.get(endpoint='price_overview', symbol='aapl')
    resp.wait()
    result = resp.data["regularMarketPrice"]["raw"]
    return str(result)


run_flask()
```

**Comment by aabmets** [comment] 2022-05-08 08:35
@Originn I would like to point out, that frequently opening and closing sessions to the Yahoo servers kills your server performance, therefore it's always the best idea to open the session once in the main method. Calls to the client methods do not have to take place inside the main method which was decorated, which is also mentioned in the official Yfrake docs.

**Comment by Originn** [comment] 2022-05-08 10:18
@aabmets Thanks it's working for me as well, by printing it on the website page. I am trying however to return the value to use it for another code in my application, and I am not yet successful. 

Does the following code return the value for you? If you can just run in as a py file, not flask.

```
@client.session
def main(user_input):
    final_list=[]
    stock_list=[]
    stock_list.append(user_input)
    queries=[]
    for i in stock_list:
        queries.append(dict(endpoint='price_overview', symbol=i))
    results = client.batch_get(queries)
    for resp in results.gather():
        final_list.append(resp.data["regularMarketPrice"]["raw"])
    return final_list

stock = main('aapl')
print(stock)
```

**Comment by aabmets** [comment] 2022-05-08 10:23
@Originn How are you running your Flask app? From the command line with 'flask run', or with Gunicorn?

**Comment by Originn** [comment] 2022-05-08 10:27
@aabmets I am using the command line 'flask run', there's also a published website that uses Gunicorn but the yfrake code is not yet implemented there.

**Comment by aabmets** [comment] 2022-05-08 10:44
@Originn 
Does this solution work for you?
```
from yfrake.client import session
from yfrake import client
import asyncio
import sys


# Need to change the event loop policy if running on Windows
if sys.platform == 'win32':
    policy = asyncio.WindowsSelectorEventLoopPolicy()
    asyncio.set_event_loop_policy(policy)


# Open session to Yahoo servers
session.open_thread()


def get_prices(*symbols):
    queries = list()
    for symbol in symbols:
        query = dict(endpoint='price_overview', symbol=symbol)
        queries.append(query)
        
    results = client.batch_get(queries)

    out = list()
    for resp in results.gather():
        data = resp.data["regularMarketPrice"]["raw"]
        out.append(data)
    return out


prices: list = get_prices('aapl', 'msft', 'tsla')
print(prices)


# Close session to Yahoo servers
session.close_thread()
```

**Comment by aabmets** [comment] 2022-05-08 10:48
@Originn 
I would like to point out that your example code was using the **_client.batch_get_** method to fetch a single request, while it's useful for fetching multiple requests, with either the same data for multiple symbols or multiple data for the same symbol.

**Comment by Originn** [comment] 2022-05-08 11:46
@aabmets Many thanks it does work and what I needed. Is there a performance difference is using it with session.open_thread()  versus @client.session?

Agree about the client.batch_get I was trying to debug my code and ended with only single request.

**Comment by aabmets** [comment] 2022-05-08 12:05
@Originn It depends how you use the session object. The session should be opened at the beginning of your program and closed at the end of your program. If you open and close the session for each request, then your performance is going to suffer.

EDIT: The `@client.session` decorator automatically opens and closes the session for you, selects between threaded and async modes and configures the asyncio event loop policy. Using the session object directly requires you to manually use the correct session functions for sync and async modes and configure the asyncio event loop manually. Otherwise there are no differences if the abovementioned is taken into consideration.

The source code of Yfrake is well documented, so if you were to read how the decorator and session are implemented, you would find that the decorator acts as a simple wrapper around the session object.

**Comment by aabmets** [comment] 2022-05-08 17:38
I'm assuming this issue has been resolved. 
Feel free to reopen it or raise a new issue should the need arise.

**Closed as completed by aabmets** 2022-05-08 17:38 UTC
Labels: question
